# ---------- Builder ----------
FROM node:20-slim AS builder

WORKDIR /app

RUN corepack enable \
    && corepack prepare pnpm@10.18.2 --activate \
    && pnpm config set node-linker hoisted

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY . .

RUN pnpm build


# ---------- Runner ----------
FROM node:20-slim AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3030

CMD ["node", "server.js"]